# https://docs.helix-editor.com/editor.html
theme = "rose_pine"
[editor]
end-of-line-diagnostics = "disable"
true-color = true
cursorline = true
rulers = [80, 120]
path-completion = true
inline-diagnostics.cursor-line = "disable"
inline-diagnostics.other-lines = "disable"
trim-trailing-whitespace = true
gutters = ["diagnostics", "diff"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[editor.statusline]
right = ["diagnostics", "position", "file-encoding"]

# https://www.reddit.com/r/HelixEditor/comments/1q7c06j/comment/nyelv91/
  [keys.normal]
  # Change file picker from Space+f to Ctrl+p
  C-p = "file_picker"

  # Or use a different leader key combo
  # Example: Use Space+o instead
  [keys.normal.space]
  o = "file_picker"

#  Common file-related commands you can remap:

# keys.normal]
 # C-p = "file_picker"              # Open file picker
 #  C-o = "file_picker_in_current_directory"  # Open in current dir
 #  C-b = "buffer_picker"            # Switch buffers
 #  C-s = ":w"                       # Save file

 #  [keys.normal.space]
 #  f = "file_picker"                # Space+f (default)
 #  b = "buffer_picker"              # Space+b (default)


[editor.file-picker]
hidden = false
git-ignore = true
